file_format: "1"
id: bendover
name: Bendover
type: shield
url: https://github.com/kneecrust/zmk-config
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - bendover_left
  - bendover_right
