manifest:
  remotes:
    - name: kneecrust
      url-base: https://github.com/kneecrust
  projects:
    - name: zmk
      remote: kneecrust
      revision: first-attempt
      import: app/west.yml
  self:
    path: config
