manifest:
  remotes:
    - name: kneecrust
      url-base: https://github.com/kneecrust
  projects:
    - name: zmk
      remote: kneecrust
      revision: main
      import: config/west.yml
  self:
    path: config
